name = "NumLeanPerf"
version = "0.1.0"
defaultTargets = ["numleanperf"]

[[lean_lib]]
name = "NumLeanPerf"

[[lean_exe]]
name = "numleanperf"
root = "Main"

[[lean_exe]]
name = "float-array-sum-bench"
root = "NumLeanPerf.Bench.FloatArraySumBench"

[[lean_exe]]
name = "float-array-add-bench"
root = "NumLeanPerf.Bench.FloatArrayAddBench"
